export type Stage = "spotted" | "reviewing" | "outreach" | "pipeline";
export const STAGES: { id: Stage; label: string }[] = [{ id: "spotted", label: "Spotted" }, { id: "reviewing", label: "Reviewing" }, { id: "outreach", label: "Outreach" }, { id: "pipeline", label: "Pipeline" }];
export type Opportunity = { id: string; ref: string; type: string; score: number; title: string; fullTitle?: string; owner: string; location: string; timing: string; timingIcon: "calendar" | "clock"; daysLeft: number | null; phaseTag: string; inScan: boolean; stage: Stage | null; watched: boolean; dismissed: boolean; value?: number; category?: string; sourceId?: string; deadlineText?: string; overview?: string; insight?: string; matchPercent?: number; relevance?: { text: string; kind: "match" | "constraint"; strong?: string }[]; involved?: { primary: string; secondary: string }; projectType?: { primary: string; secondary: string }; scale?: { primary: string; secondary: string }; currentStage?: { primary: string; secondary: string }; documents?: { name: string; kind: "pdf" | "doc" }[]; serviceLine?: string; pipelineTime?: string; pipelineNote?: string; pipelineTags?: string[]; assignee: string; contactRole?: string };
export const USER = { name: "Sarah Mitchell", firstName: "Sarah", initials: "SM", email: "sarah.mitchell@seeda.example" };
const common = { owner: "City of Calgary", location: "Calgary, AB", timingIcon: "calendar" as const, inScan: true, watched: false, dismissed: false, assignee: "SM" };
export const SEED_OPPORTUNITIES: Opportunity[] = [
  { ...common, id: "bow-river-wtp", ref: "OPP-2026-041", type: "Tender", score: 94, title: "Bow River Water Treatment Plant", fullTitle: "Bow River Water Treatment Plant Expansion", phaseTag: "Tender", timing: "Closes in 9 days", daysLeft: 9, value: 42000000, stage: "outreach", category: "Water Treatment", sourceId: "CT-8841", deadlineText: "October 3, 2026", overview: "The City of Calgary is seeking qualified partners for a major expansion of the Bow River Water Treatment Plant, including new high-rate clarification and filtration capacity.", insight: "A strong match for your municipal treatment track record, with a clear opening through the technical design scope.", matchPercent: 94, relevance: [{ text: "Municipal water treatment experience", kind: "match", strong: " aligns directly" }, { text: "Project scale fits target profile", kind: "match" }, { text: "Alberta registration required", kind: "constraint" }, { text: "Submission deadline is approaching", kind: "constraint" }], involved: { primary: "City of Calgary", secondary: "Owner and procurement authority" }, projectType: { primary: "Design-build", secondary: "Treatment capacity expansion" }, scale: { primary: "$42M estimated", secondary: "220 ML/day additional capacity" }, currentStage: { primary: "Open tender", secondary: "Questions due September 27" }, documents: [{ name: "Tender_Requirements.pdf", kind: "pdf" }, { name: "Site_Information.doc", kind: "doc" }], serviceLine: "Water Infrastructure", pipelineTags: ["RFP", "Priority"], pipelineTime: "Updated 2m ago", contactRole: "Procurement team" },
  { ...common, id: "red-deer-reuse", ref: "OPP-2026-039", type: "Grant", score: 88, title: "Red Deer Water Reuse Program", phaseTag: "Funding", timing: "Closes in 18 days", daysLeft: 18, value: 12500000, stage: "reviewing", category: "Water Reuse", sourceId: "AB-GW-221", deadlineText: "October 12, 2026", overview: "A regional funding opportunity supporting water reuse and conservation infrastructure across central Alberta.", insight: "Your reuse feasibility work makes this a credible partnership lead.", matchPercent: 88, relevance: [{ text: "Water reuse is a stated priority", kind: "match" }, { text: "Regional delivery partner needed", kind: "match" }, { text: "Matching funds required", kind: "constraint" }], involved: { primary: "Red Deer County", secondary: "Regional program sponsor" }, projectType: { primary: "Grant program", secondary: "Reuse feasibility and pilots" }, scale: { primary: "$12.5M program", secondary: "Multiple regional sites" }, currentStage: { primary: "Expressions of interest", secondary: "Applications accepted" }, documents: [{ name: "Program_Guide.pdf", kind: "pdf" }], serviceLine: "Advisory", pipelineTime: "Updated 1h ago" },
  { ...common, id: "fort-mcmurray-pump", ref: "OPP-2026-037", type: "RFQ", score: 76, title: "Fort McMurray Pump Station Upgrade", phaseTag: "Early Stage", timing: "Posted 3 hours ago", daysLeft: null, value: 6800000, stage: "spotted", category: "Wastewater", sourceId: "RM-1029", deadlineText: "November 4, 2026", overview: "Prequalification for engineering and construction services related to a lift station modernization program.", insight: "Worth watching while the procurement path becomes clearer.", matchPercent: 76, relevance: [{ text: "Strong wastewater fit", kind: "match" }, { text: "Procurement scope is not yet defined", kind: "constraint" }], involved: { primary: "Regional Municipality of Wood Buffalo", secondary: "Municipal owner" }, projectType: { primary: "Prequalification", secondary: "Pump station upgrades" }, scale: { primary: "$6.8M estimated", secondary: "Three lift stations" }, currentStage: { primary: "RFQ posted", secondary: "Prequalification phase" }, documents: [{ name: "RFQ_Notice.pdf", kind: "pdf" }], serviceLine: "Wastewater", pipelineTime: "Updated 3h ago" },
  { ...common, id: "lethbridge-biosolids", ref: "OPP-2026-034", type: "News", score: 67, title: "Lethbridge Biosolids Facility", phaseTag: "Market Signal", timing: "Posted yesterday", daysLeft: null, value: 18000000, stage: null, category: "Biosolids", sourceId: "NEWS-441", overview: "Council has approved preliminary planning for a new biosolids processing facility.", insight: "An early signal to monitor before a formal procurement appears.", matchPercent: 67, serviceLine: "Environmental Services", pipelineTime: "Updated 1d ago" },
  { ...common, id: "medicine-hat-network", ref: "OPP-2026-031", type: "Tender", score: 91, title: "Medicine Hat Distribution Network", phaseTag: "Tender", timing: "Closes in 5 days", daysLeft: 5, value: 9700000, stage: "pipeline", category: "Distribution", sourceId: "MH-7752", deadlineText: "September 29, 2026", overview: "Water distribution network rehabilitation and pressure management improvements.", insight: "A late-stage opportunity with a tight submission window.", matchPercent: 91, serviceLine: "Water Infrastructure", pipelineNote: "Outreach Sent", pipelineTime: "Sent 2h ago", pipelineTags: ["RFP"], contactRole: "Infrastructure director" },
];
export const RECENT_ACTIVITY = [{ text: "Bow River WTP moved to outreach drafting", when: "12 minutes ago", active: true }, { text: "Medicine Hat Distribution Network added to pipeline", when: "2 hours ago", active: false }, { text: "Red Deer Water Reuse Program marked for review", when: "Yesterday", active: false }];
export const PROJECT_REFERENCES = [{ id: "r1", label: "Calgary North Water Upgrade", sentence: "Our team recently delivered the Calgary North Water Upgrade, with a focus on constructability and phased commissioning." }, { id: "r2", label: "Edmonton reuse feasibility", sentence: "We also supported a reuse feasibility study in Edmonton that translated pilot findings into an implementable capital plan." }];
